name: Caller Workflow

on:
  push:

jobs:
  pre-call-workflows:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start"

  call-workflow-remote:
    needs: pre-call-workflows
    uses: lucetre/action-reusable-workflow/.github/workflows/callee.yaml@main
    with:
      username: outsider
    secrets:
      SECRET_SEED: world
  
  call-workflow-local:
    needs: pre-call-workflows
    uses: ./.github/workflows/callee.yaml
    with:
      username: mona
    secrets:
      SECRET_SEED: seed
  
  post-call-workflows:
    needs: [call-workflow-remote, call-workflow-local]
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
