name: Caller Workflow

on:
  push:

jobs:
  call-workflow-1:
    uses: lucetre/action-reusable-workflow/.github/workflows/callee.yaml@latest
    with:
      username: outsider
    secrets:
      SECRET_SEED: world
  
  call-workflow-2:
    uses: ./.github/workflows/callee.yaml
    with:
      username: mona
    secrets:
      SECRET_SEED: seed
  
  post-call:
    needs: [call-workflow-1, call-workflow-2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "DONE"
