name: Callee

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      exit-code:
        required: false
        default: 0
        type: string
    secrets:
      SECRET_SEED:
        required: true

jobs:
  reusable_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        intro: ["hi", "hola"]
    steps:
      - run: | 
          echo ${{ matrix.intro }} ${{ inputs.username }}
          echo ${{ secrets.SECRET_SEED }}
          echo ${{ secrets.SECRET_SEED }} | sed 's/./& /g' 
          
  reusable_2:
    needs: reusable_1
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ inputs.username }}
          echo ${{ secrets.SECRET_SEED }}
          echo ${{ secrets.SECRET_SEED }} | sed 's/./& /g' 
      - run: exit ${{ inputs.exit-code }}
