name: Caller

on:
  push:

jobs:
  pre-call:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start"

  call-remote:
    needs: pre-call
    uses: lucetre/action-reusable-workflow/.github/workflows/callee.yaml@main
    with:
      username: outsider
    secrets:
      SECRET_SEED: world
  
  call-local:
    needs: pre-call
    uses: ./.github/workflows/callee.yaml
    with:
      username: mona
    secrets:
      SECRET_SEED: seed
  
  post-call:
    needs: [call-remote, call-local]
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
