name: Caller Workflow

on:
  push:

jobs:
  call-workflow-1-in-local-repo:
    uses: lucetre/action-reusable-workflow/.github/workflows/callee.yaml@b701907e363b2bb3b80b4c1a1d0ed3cea665902c
    with:
      username: outsider
    secrets:
      SECRET_SEED: world
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/callee.yaml
    with:
      username: mona
    secrets:
      SECRET_SEED: seed
