name: Reusable Workflow

on:
  push:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      SECRET_SEED:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ inputs.username }}
          echo ${{ github.sha }}
          echo ${{ secrets.SECRET_SEED }}
          echo ${{ secrets.SECRET_SEED }} | sed 's/./& /g' 
