name: Caller

on:
  workflow_dispatch:

jobs:
  pre-call:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start"

  remote:
    needs: pre-call
    uses: lucetre/action-reusable-workflow/.github/workflows/callee.yaml@test-script
    with:
      username: outsider
    secrets:
      SECRET_SEED: world

  local:
    needs: pre-call
    uses: ./.github/workflows/callee.yaml
    with:
      username: mona
    secrets:
      SECRET_SEED: seed

  post-call-success:
    if: success()
    needs: [remote, local]
    runs-on: ubuntu-latest
    steps:
      - run: echo "success"

  post-call-failure:
    if: failure()
    needs: [remote, local]
    runs-on: ubuntu-latest
    steps:
      - run: echo "failure"
