name: Callee

on:
  push:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      SECRET_SEED:
        required: true

jobs:
  reusable_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        intro: ["hi", "hola"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: test-script
      - run: |
          echo ${{ matrix.intro }} ${{ inputs.username }}
          echo ${{ secrets.SECRET_SEED }}
          echo ${{ secrets.SECRET_SEED }} | sed 's/./& /g' 
          bash test-script.sh

  reusable_2:
    needs: reusable_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: test-script
      - run: |
          echo ${{ inputs.username }}
          echo ${{ secrets.SECRET_SEED }}
          echo ${{ secrets.SECRET_SEED }} | sed 's/./& /g'
          bash test-script.sh
