name: Caller Workflow

on:
  push:

jobs:
  call-workflow-1:
    uses: lucetre/action-reusable-workflow/.github/workflows/callee.yaml@main
    with:
      username: outsider
    secrets:
      SECRET_SEED: world
  
  call-workflow-2:
    uses: ./.github/workflows/callee.yaml
    with:
      username: mona
    secrets:
      SECRET_SEED: seed
  
  call-workflow-3:
    uses: ./.github/workflows/another-callee.yaml
    with:
      username: mona
    secrets:
      SECRET_SEED: seed
